### ISSUE TITLE
Information in `pyproject.toml` out of date

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#897]
```toml
[project.urls]
homepage = "https://github.com/kjaymiller/render_engine/"
repository = "https://github.com/kjaymiller/render_engine/"
documentation = "https://render-engine.readthedocs.io/en/latest/"
```

should be 

```toml
[project.urls]
homepage = "https://github.com/render-engine/render-engine/"
repository = "https://github.com/render-engine/render-engine/"
documentation = "https://render-engine.readthedocs.io/en/latest/"
```
